-- ── Supabase PostgreSQL Database Setup Script ───────────────────────
-- Run this script in your Supabase SQL Editor:
-- Go to: https://supabase.com/dashboard/project/jtnzjmcejnmeyyzeqcel/sql/new

-- 1. Create USERS table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL DEFAULT '',
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'patient' CHECK (role IN ('patient', 'admin')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create APPOINTMENTS table
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  condition_type TEXT NOT NULL,
  contact TEXT NOT NULL DEFAULT '',
  notes TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Indexes for high performance
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_appointments_user_id ON public.appointments(user_id);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON public.appointments(status);

-- 4. Enable Row Level Security (RLS) & Grant access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Drop old policies if existing
DROP POLICY IF EXISTS "Allow all operations on users" ON public.users;
DROP POLICY IF EXISTS "Allow all operations on appointments" ON public.appointments;

-- Create permissive policies for server & API access
CREATE POLICY "Allow all operations on users" ON public.users
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all operations on appointments" ON public.appointments
  FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON public.users TO anon, authenticated, service_role;
GRANT ALL ON public.appointments TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 5. Seed default Admin user (email: admin@clinic.com / password: admin123)
INSERT INTO public.users (name, email, phone, password_hash, role)
VALUES (
  'Admin',
  'admin@clinic.com',
  '+92 300 1234567',
  '$2a$12$a1/9.O6NnIuXfP4S4P0h.eN1vL60U8d3kX0sH8l/eFv7jQ3K1u2eC',
  'admin'
)
ON CONFLICT (email) DO NOTHING;
